# Generated by Django 5.2.3 on 2025-06-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='weigth',
            new_name='weight',
        ),
    ]
