# Generated by Django 5.2.3 on 2025-07-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_quotes_dislikes_alter_quotes_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotelike',
            old_name='type',
            new_name='vote_type',
        ),
    ]
