# Generated by Django 5.2.3 on 2025-07-02 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_type_quotelike_vote_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
